import React, { useState, useEffect, useRef } from 'react'
import { TextInput, ScrollArea, Text, Badge, Loader, Button, Group } from '@mantine/core'
import { useDebouncedValue } from '@mantine/hooks'
import { IconSearch, IconBrandGoogle, IconFolderOpen, IconArrowRight, IconMessageCircle2, IconClock } from '@tabler/icons-react'
import ReactMarkdown from 'react-markdown'

// Bindings automatically generated by Wails
// @ts-ignore
import { SearchThreads, GetThreadMessages, OpenPath, OpenURL } from '../wailsjs/go/main/App'

interface ThreadResult {
  id: string
  title: string
  startedAt: number
  source: string
  score: number
  snippet: string
  matches: string[]
  filePath: string
  webUrl: string
}

interface Message {
  role: string
  content: string
  toolName: string
  toolCalls: string
  timestamp: number
}

export default function App() {
  const [query, setQuery] = useState('')
  const [debouncedQuery] = useDebouncedValue(query, 300)
  const [threads, setThreads] = useState<ThreadResult[]>([])
  const [selectedThread, setSelectedThread] = useState<ThreadResult | null>(null)
  const [messages, setMessages] = useState<Message[]>([])
  const [loading, setLoading] = useState(false)
  const [messagesLoading, setMessagesLoading] = useState(false)

  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Initial load
  useEffect(() => {
    performSearch('')
  }, [])

  // Debounced search
  useEffect(() => {
    performSearch(debouncedQuery)
  }, [debouncedQuery])

  const performSearch = async (q: string) => {
    setLoading(true)
    try {
      const results = await SearchThreads(q)
      setThreads(results || [])
    } catch (err) {
      console.error('Error searching threads:', err)
    } finally {
      setLoading(false)
    }
  }

  const handleSelectThread = async (thread: ThreadResult) => {
    setSelectedThread(thread)
    setMessagesLoading(true)
    try {
      const msgs = await GetThreadMessages(thread.id)
      setMessages(msgs || [])
    } catch (err) {
      console.error('Error fetching messages:', err)
    } finally {
      setMessagesLoading(false)
    }
  }

  // Scroll to bottom when messages load/change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const handleOpenWeb = (thread: ThreadResult) => {
    if (thread.webUrl) {
      OpenURL(thread.webUrl)
    } else {
      // Fallback web URL construction if it matches a UUID or typical ID
      OpenURL(`https://gemini.google.com/app/${thread.id}`)
    }
  }

  const handleRevealFile = (thread: ThreadResult) => {
    if (thread.filePath) {
      OpenPath(thread.filePath)
    }
  }

  const formatTime = (timestamp: number) => {
    if (!timestamp) return ''
    // Handle python float timestamps or standard unix millisecond/second
    let date = new Date(timestamp * 1000)
    if (timestamp > 1e11) {
      // already in milliseconds
      date = new Date(timestamp)
    }
    return date.toLocaleString(undefined, {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  return (
    <div className="app-container">
      {/* Sidebar Panel */}
      <div className="sidebar">
        <div className="sidebar-header">
          <Group justify="space-between" mb="md">
            <Text fw={800} size="lg" c="blue.5">
              Thread OS
            </Text>
            <Badge variant="outline" size="sm">
              {threads.length} threads
            </Badge>
          </Group>
          <TextInput
            className="search-input"
            placeholder="Search threads and contents..."
            value={query}
            onChange={(e) => setQuery(e.currentTarget.value)}
            leftSection={<IconSearch size={16} stroke={1.5} />}
            rightSection={loading ? <Loader size="xs" /> : null}
          />
        </div>

        <div className="thread-list-container">
          <ScrollArea h="100%" scrollbarSize={6}>
            {threads.length === 0 && !loading && (
              <Text size="sm" c="dimmed" ta="center" mt="xl">
                No threads found
              </Text>
            )}
            {threads.map((t) => {
              const isActive = selectedThread?.id === t.id
              return (
                <div
                  key={t.id}
                  className={`thread-item ${isActive ? 'active' : ''}`}
                  onClick={() => handleSelectThread(t)}
                >
                  <div className="thread-item-title">
                    {t.title || 'Untitled Thread'}
                  </div>
                  <div className="thread-item-meta">
                    <span className={`source-badge source-${t.source}`}>
                      {t.source || 'local'}
                    </span>
                    <Group gap={4} c="dimmed" style={{ fontSize: '0.72rem' }}>
                      <IconClock size={10} />
                      <span>{formatTime(t.startedAt)}</span>
                    </Group>
                  </div>
                  {t.snippet && (
                    <div className="thread-item-snippet">
                      {t.snippet}
                    </div>
                  )}
                  {t.matches && t.matches.length > 0 && (
                    <div className="thread-item-matches">
                      {t.matches.map((m, idx) => (
                        <div
                          key={idx}
                          className="thread-item-match-line"
                          dangerouslySetInnerHTML={{ __html: m }}
                        />
                      ))}
                    </div>
                  )}
                </div>
              )
            })}
          </ScrollArea>
        </div>
      </div>

      {/* Main Content / Viewer Panel */}
      <div className="main-content">
        {selectedThread ? (
          <>
            {/* Thread Header */}
            <div className="viewer-header">
              <div>
                <div className="viewer-title">{selectedThread.title}</div>
                <div className="viewer-meta">
                  Started {formatTime(selectedThread.startedAt)} • Source: {selectedThread.source || 'local'}
                </div>
              </div>
              <div className="viewer-actions">
                <Button
                  variant="light"
                  color="blue"
                  size="sm"
                  leftSection={<IconBrandGoogle size={16} />}
                  onClick={() => handleOpenWeb(selectedThread)}
                >
                  Open on Web
                </Button>
                {selectedThread.filePath && (
                  <Button
                    variant="light"
                    color="gray"
                    size="sm"
                    leftSection={<IconFolderOpen size={16} />}
                    onClick={() => handleRevealFile(selectedThread)}
                  >
                    Reveal File
                  </Button>
                )}
              </div>
            </div>

            {/* Messages Scroll Area */}
            <div className="messages-list">
              {messagesLoading ? (
                <div className="welcome-view">
                  <Loader size="lg" />
                  <Text size="sm" c="dimmed" mt="md">Loading thread content...</Text>
                </div>
              ) : (
                <>
                  {messages.map((msg, index) => {
                    const isUser = msg.role === 'user'
                    const isAssistant = msg.role === 'assistant'
                    const isTool = msg.role === 'tool'
                    
                    let bubbleClass = 'message-bubble assistant'
                    if (isUser) bubbleClass = 'message-bubble user'
                    if (isTool) bubbleClass = 'message-bubble tool'

                    let parsedToolCalls = []
                    if (msg.toolCalls) {
                      try {
                        parsedToolCalls = JSON.parse(msg.toolCalls)
                      } catch (e) {}
                    }

                    return (
                      <div key={index} className={bubbleClass}>
                        <div className={`message-sender ${msg.role}`}>
                          <span>{msg.role}</span>
                          {msg.timestamp > 0 && (
                            <span style={{ fontWeight: 400, opacity: 0.6 }}>
                              {formatTime(msg.timestamp)}
                            </span>
                          )}
                        </div>
                        
                        {msg.content && (
                          <div className="message-content">
                            <ReactMarkdown>{msg.content}</ReactMarkdown>
                          </div>
                        )}

                        {/* Display Tool Name & Calls */}
                        {msg.toolName && (
                          <div style={{ marginTop: msg.content ? 8 : 0 }}>
                            <Badge color="pink" variant="light">Tool call: {msg.toolName}</Badge>
                          </div>
                        )}

                        {parsedToolCalls && parsedToolCalls.length > 0 && (
                          <div className="tool-calls-container">
                            {parsedToolCalls.map((tc: any, tcIdx: number) => (
                              <div key={tcIdx} style={{ marginBottom: tcIdx > 0 ? 8 : 0 }}>
                                <div className="tool-call-header">
                                  Call: {tc.name || 'tool'}
                                </div>
                                {tc.args && (
                                  <div className="tool-call-args">
                                    {typeof tc.args === 'object' 
                                      ? JSON.stringify(tc.args, null, 2) 
                                      : String(tc.args)}
                                  </div>
                                )}
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    )
                  })}
                  <div ref={messagesEndRef} />
                </>
              )}
            </div>
          </>
        ) : (
          <div className="welcome-view">
            <IconMessageCircle2 size={48} stroke={1.5} />
            <h2>Select a Thread</h2>
            <Text size="sm" c="dimmed">
              Choose a conversation thread from the sidebar to view its transcript
            </Text>
          </div>
        )}
      </div>
    </div>
  )
}
