allowBuilds:
  '@github/keytar': true
  '@google/genai': true
  '@heroui/shared-utils': true
  better-sqlite3: true
  cline: true
  esbuild: set this to true or false
  node-pty: true
  openclaw: true
  protobufjs: true
  tree-sitter-bash: true
overrides:
  ai-os: 'link:'
