// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetThreadMessages(arg1) {
  return window['go']['main']['App']['GetThreadMessages'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SearchThreads(arg1) {
  return window['go']['main']['App']['SearchThreads'](arg1);
}
