// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetThreadMessages(arg1:string):Promise<Array<main.Message>>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SearchThreads(arg1:string):Promise<Array<main.ThreadResult>>;
